import os
import logging
import requests
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv
import re
import html # Required for robust text escaping

load_dotenv()
logger = logging.getLogger(__name__)

def sanitize_md_to_tg_html(text: str) -> str:
    """Sanitize LLM Markdown output to prevent Telegram HTML parse mode crashes."""
    if not text:
        return text
    
    # STEP 1: Escape all dangerous HTML characters (Convert < to &lt;, > to &gt;)
    # This safely handles medical metrics like heart rate "<138 bpm"
    text = html.escape(text)

    # STEP 2: After securing the text, revert Markdown syntax into valid Telegram HTML tags
    
    # Restore bold tags generated by AI if they were escaped
    text = text.replace("&lt;b&gt;", "<b>").replace("&lt;/b&gt;", "</b>") 
    
    # Process Markdown bold asterisks (they are normal asterisks now due to escape)
    text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', text)
    
    # Process Markdown headers
    text = re.sub(r'(?m)^#{1,6}\s*(.*)', r'<b>\1</b>', text)
    
    # Process Markdown bullet points
    text = re.sub(r'^(\s*)[*+-]\s+', r'\1• ', text, flags=re.MULTILINE)

    return text

def send_telegram_msg(chat_id, text):
    """Send formatted message via Telegram Bot API."""
    token = os.getenv("TELEGRAM_BOT_TOKEN")
    if not token:
        logger.error("[TELEGRAM] No token found in environment variables.")
        return

    url = f"https://api.telegram.org/bot{token}/sendMessage"
    
    # Inject text through the Sanitizer middleware before packaging
    safe_text = sanitize_md_to_tg_html(text)
    
    payload = {
        "chat_id": chat_id,
        "text": safe_text,
        "parse_mode": "HTML" 
    }
    
    try:
        response = requests.post(url, json=payload)
        
        # [FALLBACK] Rescue the message if broken HTML tags still manage to slip through
        if response.status_code == 400 and "parse entities" in response.text:
            logger.warning(f"[TELEGRAM] HTML parse failed. Fallback to raw text. Error: {response.text}")
            payload.pop("parse_mode") 
            response = requests.post(url, json=payload)
            
        if response.status_code != 200:
            logger.error(f"[TELEGRAM] Failed to send message: {response.text}")
            
    except Exception as e:
        logger.error(f"[TELEGRAM] Connection error: {e}")

def send_typing_action(chat_id):
    """
    Send 'typing...' indicator to Telegram immediately.
    Call this at the start of any slow operation so user gets instant feedback.
    The indicator auto-expires after 5 seconds on Telegram's side.
    """
    token = os.getenv("TELEGRAM_BOT_TOKEN")
    if not token:
        return
    try:
        requests.post(
            f"https://api.telegram.org/bot{token}/sendChatAction",
            json={"chat_id": chat_id, "action": "typing"},
            timeout=3
        )
    except Exception:
        pass  # Non-critical: silently ignore if this fails

def send_html_email(subject, html_content, config):
    """Sends an HTML email report using SMTP configuration."""
    email_cfg = config.get("email_config", {})
    if not email_cfg.get("enabled"): return

    env_sender = os.getenv("EMAIL_SENDER")
    env_password = os.getenv("EMAIL_PASSWORD")
    env_receiver = os.getenv("EMAIL_RECEIVER")
    
    if not all([env_sender, env_password, env_receiver]):
        logger.error("[EMAIL] Missing EMAIL_SENDER/PASSWORD/RECEIVER in .env")
        return

    try:
        smtp_server = email_cfg.get('smtp_server', 'smtp.gmail.com')
        smtp_port = int(email_cfg.get('smtp_port', 587))

        msg = MIMEMultipart()
        msg['From'] = env_sender       
        msg['To'] = env_receiver       
        msg['Subject'] = subject
        msg.attach(MIMEText(html_content, 'html'))

        server = smtplib.SMTP(smtp_server, smtp_port)
        server.starttls()
        server.login(env_sender, env_password)
        server.send_message(msg)
        server.quit()
        
        logger.info(f"[EMAIL] Sent report to {env_receiver}")
    except Exception as e:
        logger.error(f"[EMAIL] Failed to send email: {e}")